project:
  type: website
  output-dir: docs

website:
  title: "film-dataset"
  navbar:
    right:
      - text: "Overview"
        href: overview.qmd
      - text: "Film Clips"
        menu:
          - text: "[AkeelahBee] Akeelah and the Bee"
            href: AkeelahBee.qmd
          - text: "[BealeStreet] If Beale Street Could Talk"
            href: BealeStreet.qmd
          - text: "[CatchMe] Catch Me If You Can"
            href: CatchMe.qmd
          - text: "[DaysSummer] 500 Days of Summer"
            href: DaysSummer.qmd
          - text: "[Fences] Fences"
            href: Fences.qmd
          - text: "[ForrestGump] Forrest Gump"
            href: ForrestGump.qmd
          - text: "[GoodWill] Good Will Hunting"
            href: GoodWill.qmd
          - text: "[GreenMile] The Green Mile"
            href: GreenMile.qmd
          - text: "[KingsSpeech] The King's Speech"
            href: KingsSpeech.qmd
          - text: "[LadyBird] Lady Bird"
            href: LadyBird.qmd
          - text: "[PursuitHappyness] The Pursuit of Happyness"
            href: PursuitHappyness.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



