project:
  type: website

website:
  title: "film-dataset"
  navbar:
    left:
      - text: "Overview"
        href: overview.qmd
      - text: "Film Clips"
        menu:
          - text: "Akeelah"
            href: akeelah.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



