project:
  type: website
  output-dir: docs

website:
  title: "film-dataset"
  navbar:
    left:
      - text: "Overview"
        href: overview.qmd
      - text: "Film Clips"
        menu:
          - text: "[AkeelahBee] Akeelah and the Bee"
            href: AkeelahBee.qmd
          - text: "[BealeStreet] If Beale Street Could Talk"
            href: BealeStreet.qmd
          - text: "[CatchMe] Catch Me If You Can"
            href: CatchMe.qmd
          - text: "[DaysSummer] 500 Days of Summer"
            href: DaysSummer.qmd
          - text: "[Fences] Fences"
            href: Fences.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



